version: '3'

services:

  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend/public/images:/public/images
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/
    ports:
      - 8081:8081

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 8080:3000

  mongo:
    image: mongo:8.0.0-rc9-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./backend/database/mongodata:/data/db
    ports:
      - 2772:27017

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
